#include<stdio.h>

typedef enum{
    LE=257,GE,EQ,NE,AND,OR,NOT,
    MAIN,VOID,INT,CHAR,WHILE,IF,ELSE,RETURN,BREAK,CONTINUE,
    NUMBER,CHARCONSTANT,STRING,IDENTIFIER,OPERATOR

}tokenType;


char* token_list[]=
{
    "LE","GE","EQ","NE","AND","OR","NOT",
    "MAIN","VOID","INT","CHAR","WHILE","IF","ELSE","RETURN","BREAK","CONTINUE",
    "NUMBER","CHARCONSTANT","STRING","IDENTIFIER","OPERATOR"
};

